### ISSUE TITLE
GH actions fails to add to Board at times

### ISSUE THREAD

**Issue by tjjalava** [Yleisradio/gh-project-actions#1]
Steppi, jossa tarkistetaan onko issue jo projektissa ei aina toimi. GraphQL-kysely palauttaa listan jossa haluttua issue-id:tä ei ole, vaikka issue on jo projektissa. 

[Täällä](https://github.com/Yleisradio/gh-project-actions/blob/625adc9f060173429bcf54cc08e7dd2a9f865007/issues-to-project/issues_to_project.sh#L38) ilmeisesti asetetaan jokin limiitti sille montako riviä kysely palauttaa? Se voisi ehkä olla syy ongelmaan. Mutta kun en mitään noista kyselyistä tajua, niin jaa-a..

Sinänsä tämä ei ole paha ongelma, skripti yrittää lisätä issuen uudestaan taululle ja se menee läpi kiltisti, vaikka issue siellä olisikin jo,

**Comment by tjjalava** [comment]
Sain tämän esille poistamalla testi-issuen projektilta ja ajamalla actionseista workflown uudestaan, joten testisetuppi ei ehkä ollut täysin autenttinen. Ja siinäkin mielessä kyllä aika minor-ongelma, koska ei tollasta tilannetta normaalisti tule koskaan

**Comment by rpsu** [comment]
graphql kysely taitaa palauttaa vain 100 itemiä, ja isompi määrä pitäis ajaa looppina sivutuksen avulla. Sighh..

**Comment by tjjalava** [comment]
joo, no jos tohon ei ole helppoa ratkaisua, niin ei kannattane käyttää aikaa, koska tuo ei aiheuta mitään konkreettisia ongelmia

**Comment by rpsu** [comment]
juu, jos se ei hajota mitään vaiks action koettaa työntää jo projektissa olevaa issueta sinne uudestaan, niin pannaan työlistalle matalla priolla.
